[package]
name = "provisions"
version = "0.1.0"
authors = ["Jake Craige <james.craige@gmail.com>"]
edition = "2018"

[dependencies]
secp256k1 = { version = "0.12.2", features = ["rand"] }
rand = "0.6.5"
sha2 = "0.8.0"
num-bigint = "0.2"
num-traits = "0.2"
num-iter = "0.1"
num-integer = "0.1"
